const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');

const options={
    swaggerDefinition:{
        info:{
            title:'TestAPI',
            version:'1.0.0',
            description:'Test Express APO with autogenerated swagger doc',
        },
        basePath:'/',
    },
    apis:['./swagger.json'],
};

const specs = swaggerJsdoc(options);

module.exports=(app)=>{
    app.use('/api-docs',swaggerUi.serve, swaggerUi.setup(options));
}